### ISSUE TITLE
Synch Not working

### ISSUE THREAD

**Issue by JS118m** [jdgeenen/gcontactsync#126] opened 2019-01-02 17:56 UTC
Using TBird 60.4.0 (32-bit) with gcontactsync, after changing & adding contcats in both google contacts and Tbird address book then operating gcontactsync no sycnronisation takes place. Google calendar and Lightening calendar synch okay.

I've tried unintsalling and reinstalling gcontactsync but no change to the problem.

Any ideas gratefully received.

Thanks

**Comment by JerryDurand** [comment] 2019-01-02 18:18
It's a known problem, TBird broke the interface yet again.  There are hundreds of mice working on the problem now, but a group of cats keeps scattering them.

**Comment by mmalmeida** [comment] 2019-01-11 11:58
I think this is a duplicate of https://github.com/jdgeenen/gcontactsync/issues/121

**Comment by jdgeenen** [comment] 2019-03-10 14:28
Dup of #121

**Closed by jdgeenen** 2019-03-10 14:28 UTC
