### ISSUE TITLE
My contacts are synchronized to "Other Contacts" in Google Contacts

### ISSUE THREAD

**Issue by nagyt234** [jdgeenen/gcontactsync#111] opened 2017-09-28 13:26 UTC
My personal contacts from Thunderbird are synchronized to "Other Contacts" in Google Contacts instead of under "My Contacts", however the groups are synchronized there.

**Comment by jdgeenen** [comment] 2019-03-11 12:12
Duplicate of issue #60.

**Closed by jdgeenen** 2019-03-11 12:12 UTC
