### ISSUE TITLE
Not all contacts sync betwin google and thunderbird 68.8.0

### ISSUE THREAD

**Issue by PiPo-Sido** [jdgeenen/gcontactsync#156] opened 2020-05-10 20:13 UTC
Since i restart using thunderbird since this month, i also re-installed this great add-on, there is only 1 issue. It is not syncing all of my Google contacts.

In my browser my contact list is 1260 contacts, in thunderbird it only shows 760. I have try to remove the add-on, clear the cache folder of the add-on and restarted thunderbird. Then re-installed the add-on and add my account again, then it only downloads 400 contacts.

What can i do that it syncs all of my contacts?

Regards Danny

**Comment by samsong** [comment] 2020-05-14 02:35
Same for me today GContact sync asked to delete around 1500 contacts. I said OK.
After that I notice contacts missing. I reset from server but only MAX 1500 of 2400 contacts sync.

I have logging disabled as previous suggestion. It was working fine until this week.
Any changes from Google contact API?

**Comment by kevincolyer** [comment] 2020-05-14 10:11
This has started happening for me also within the last week. I did a before and after contact dump from thunderbird so will try to see what the differences are...

**Comment by colmode** [comment] 2020-05-14 17:47
See comments starting at https://github.com/jdgeenen/gcontactsync/issues/148#issuecomment-628434390

**Comment by JayBird707** [comment] 2020-05-14 18:01
I lost 2300+ contacts yesterday after years of using gContactsync without a hitch.  Same think 1500 contact limit.

**Comment by PiPo-Sido** [comment] 2020-05-14 18:10
So the best thing is to dis-able the add-on untill there is a update?

**Comment by KrasheninnikovMaxim** [comment] 2020-05-14 18:23
If there are fewer than 1500 contacts, you can use this:
https://github.com/jdgeenen/gcontactsync/issues/148#issuecomment-627541393

**Comment by Huku-Huku** [comment] 2020-05-15 17:10
Two days ago I got the message if I am sure I want to delete 1663 accounts locally. On both computers (windows). Seems like 1500 is the limit, here is the summary.

*****Synchronization Summary*****
 - Not changed: 1500
 - Conflicted: 0	(changed in Thunderbird and Google)
Changes to Thunderbird (local):
 - Added: 0
 - Updated: 0
 - Removed: 1663
 - Ignored: 0	(due to read-only mode)
Changes to Google contacts (remote):
 - Added: 0
 - Updated: 0
 - Removed: 0
 - Ignored: 0	(due to write-only mode)
*****End of summary*****

**Comment by dantehavershem** [comment] 2020-05-15 17:15
Same here in two macbooks, one iMAC and one Win7-64 system. All (1) came up with the same message  gSync has to delete 281 contacts from thunderbird. I have 1781 in Google contacts

**Comment by Mistral-75** [comment] 2020-05-15 18:10
Same here. gContactSync synchronised and proposed me to delete 631 contacts from Thunderbird. Fortunately, I refused and suspend the synchronisation.

Currently I have 2,214 contacts in the address book of my Google account and 2,131 in Thunderbird's address books. 2,131 - 631 = 1,500.

OS is Windows 10 version 1909 (18363.836)

**Comment by Bastien59960** [comment] 2020-05-15 18:24
Same for me, ask to deleted over 600 contacts !

**Comment by samsong** [comment] 2020-05-15 22:35
Bug lodged @ google contacts API
https://issuetracker.google.com/u/1/issues/156666929

**Comment by Bastien59960** [comment] 2020-05-24 20:18
DId anybody find a solution ?

**Comment by kevincolyer** [comment] 2020-05-25 09:48
Sadly no. I have moved to a different Add On: CardBook.

It replaces the addressbook with the Cardbooks own address book. This is not much of a problem. Quite a few fiddly options. But is syncs REALLY well with Google. I have three way syncing now. Very fast too.

I am sad to leave gcontact-sync - THANK YOU so much for the extension. I hope that maybe the two projects get merged! 

Kevin

CardBookvCard address bookThis add-on allows you to manage all your contacts under the vCard standard.

Version History: https://addons.thunderbird.net/en-US/thunderbird/addon/cardbook/versions
Twitter : @CardBookAddon
GitLab: CardBook
Forum: https://cardbook.icu/forum/

**Comment by SteveS73** [comment] 2020-05-27 05:00
Running Thunderbird 60.9.1 with gContactsyn 2.1.13 (the reason is the latest Lightning isn't playing nice with the latest Thunderbird). OS: Windows 10 Pro 1909 build 18363.778

For a while now, I've been having all kinds of weird synching problems including "expired tokens". Today it "deleted" 1573 local  contacts saying they had been deleted from Google. It didn't ask for permission to delete, either! I haven't had time to verify any actual deletions from Google, though a quick check showed at least some of the contacts still there that were deleted from TB address book.

I reset gContactsync to refresh from the server. I can confirm that I also get exactly 1500 contacts synched. This seems to be a hard limit since I added a dummy contact on Google and did the process again: only 1500 synched.
Hoping this can be resolved soon.....

**Comment by Filgibson** [comment] 2020-05-27 09:43
Good morning everyone. Using the same GContactSync component myself, I had the same problem. Google syncing has been limited to 1500 contacts. However, I have found a solution to bypass the problem. simply create different labels in your google account (for example divide them by letters of the alphabet or by type of contacts) and you're done. Each label will have 1500 synchronizable contacts. It is no longer possible to load more and this seems to me a solution. I am using it and it works. We have more than 2000 contacts and I have divided them into three categories so I have up to 4500 synchronizable contacts. I hope I have helped you. good job

**Comment by Filgibson** [comment] 2020-05-27 13:43
> DId anybody find a solution ?

see my post!!

**Comment by dantehavershem** [comment] 2020-05-27 13:56
to be honest I switched to cardbook ..  very easy to configure and has now problem with my  1800 contacts. works fast, easy and reliable

**Comment by Bastien59960** [comment] 2020-05-27 20:37
Cardook firts install sync to 4338 contacts..   second syn down to 1538 contacts...

**Comment by JayBird707** [comment] 2020-05-27 22:16
I finally loaded CardBook and it does not sync any distribution lists.  Anyone have a solution for this?

**Comment by Filgibson** [comment] 2020-05-28 09:49
> Esecuzione di Thunderbird 60.9.1 con gContactsyn 2.1.13 (il motivo è che l'ultimo Lightning non sta giocando bene con l'ultimo Thunderbird). Sistema operativo: Windows 10 Pro 1909 build 18363.778
> 
> Per un po 'di tempo, ho avuto tutti i tipi di strani problemi di sincronizzazione tra cui "token scaduti". Oggi ha "cancellato" 1573 contatti locali dicendo che erano stati eliminati da Google. Non ha nemmeno chiesto il permesso di cancellare! Non ho avuto il tempo di verificare eventuali cancellazioni effettive da Google, anche se un rapido controllo ha mostrato che almeno alcuni dei contatti ancora presenti sono stati eliminati dalla rubrica TB.
> 
> Ho ripristinato gContactsync per aggiornare dal server. Posso confermare che ho anche sincronizzato esattamente 1500 contatti. Questo sembra essere un limite difficile da quando ho aggiunto un contatto fittizio su Google e ho ripetuto il processo: solo 1500 sincronizzati.
> Spero che questo possa essere risolto presto .....

SEE MY POST!!

**Comment by Filgibson** [comment] 2020-05-28 09:49
> Anch'io. gContactSync sincronizzato e mi ha proposto di eliminare 631 contatti da Thunderbird. Fortunatamente, ho rifiutato e sospeso la sincronizzazione.
> 
> Attualmente ho 2.214 contatti nella rubrica del mio account Google e 2.131 nelle rubriche di Thunderbird. 2.131 - 631 = 1.500.
> 
> Il sistema operativo è Windows 10 versione 1909 (18363.836)

SEE MY POST

**Comment by samsong** [comment] 2020-05-31 10:32
Reference of a fix for a contact sync plugin
https://stackoverflow.com/a/62054304/6492825

Not sure how this can be implemented to the addon. Hope author checks this thread

**Comment by zanonmark** [comment] 2020-06-04 07:55
Attached is a working patch to be applied against 3.1.7.

It works by:
a) modifying GHttpRequest.js, adding the start-index parameter (if available) in "getAll" and "getFromGroup" calls;
b) modifying Sync.js, particularly the getContacts() and sync2() methods, essentially retrieving the start-index suggestion from every Google response and sending another request to Google itself, recursively; also, instead of an XML object, sync2() now receives an array of contact entries which is feed at every response from Google.

Please note.
In order for everything to work properly, you also need to modify the following parameters in Thunderbird:
```
dom.max_chrome_script_run_time = 0
dom.max_ext_content_script_run_time = 0
dom.max_script_run_time = 0
dom.worker.canceling.timeoutMilliseconds = 300000 // not 0

```
The last one was driving me mad, because it was not documented elsewhere. You must increase the default value (30000 = 30 sec, so I set 300000 = 5 min), otherwise the SyncWorker.js code will die when trying to synchronize a huge amount of contacts (approximately > 2000). Setting 0 won't work here, as the worker will stop after a few moments.

**DO A FULL BACKUP OF YOUR CONTACTS BEFORE RUNNING!**

MZ
[mzpatch.txt](https://github.com/jdgeenen/gcontactsync/files/4728417/mzpatch.txt)

**Comment by samsong** [comment] 2020-06-06 03:00
@zanonmark can you or someone build a forked version of contact sync with the patch?
Or advise how we can do it?

**Comment by zanonmark** [comment] 2020-06-06 10:23
@samsong The steps are:
* "Clone or download" the repository into a local directory on your pc;
* run `git apply` to apply the patch, which will modify those 2 files;
* run `./build.sh` to create the .xpi extension package to be installed in Thunderbird.

If you don't feel at home working with git, I'm attaching a patched version (it is called 3.1.7, but I should have called it 3.1.7.1 or the like - but that's up to the maintainer).
Just rename the .zip to .xpi, as github won't allow such extensions.

MZ

[gContactSync-3.1.7.zip](https://github.com/jdgeenen/gcontactsync/files/4739811/gContactSync-3.1.7.zip)

**Comment by colmode** [comment] 2020-06-06 11:41
Since you have the patch; how about starting a new pull request with that applied? That way the maintainer can review and merge it easily.

**Comment by jdgeenen** [comment] 2020-06-06 11:53
@zanonmark Thanks for the patch, and that undocumented preference.  I'll add that pref to the Preferences GUI in a separate issue.

I'll look into applying and testing these changes this weekend.

**Comment by zanonmark** [comment] 2020-06-06 16:53
@colmode Thanks for the advice, I didn't know much about pull requests, so here's my first one.

@jdgeenen Thanks.

**Closed** 2020-06-07 01:38 UTC
Labels: bug

**Comment by jdgeenen** [comment] 2020-06-07 02:18
@zanonmark Thanks!

I uploaded Version 3.2.0 with this fix to addons.thunderbird.net and pushed to the repo. Direct download link: https://github.com/jdgeenen/gcontactsync/raw/master/downloads/gContactSync-3.2.0.xpi

**Comment by samsong** [comment] 2020-06-07 03:41
Confirm issue fixed. 2968 contacts synced.

@jdgeenen Thunderbird addon repository not updated yet, still 3.17
I downloaded & installed XPI manually

Thanks

**Comment by zanonmark** [comment] 2020-06-07 08:57
Thanks for the new release!

MZ

**Comment by Krishna5907** [comment] 2020-07-14 16:22
Excellent,

I had Synced 1553 Contacts in one Group

**Comment by mzealey** [comment] 2020-07-19 18:10
This works when installed manually, however 3.1.7 is still the latest version via the add-on store

**Comment by jmspar** [comment] 2020-08-17 09:55
Many thanks, for this and for all the work before!
Hope this will get to the add-on store soon (but manual install worked, in the meanwhile).

**Comment by laggarcia** [comment] 2020-08-23 15:01
> This works when installed manually, however 3.1.7 is still the latest version via the add-on store

Any plans to roll this out to the Thunderbird add-on store?

**Comment by dgrunberg** [comment] 2020-09-23 16:18
I have downloaded and installed 3.2.0 version, and when I sync (after removing local AB), I get only 1209 entries, my Google AB has 1887.  Is this the same issue or a different one?  Using TB 68.10.0 on Linux.

**Comment by Krishna5907** [comment] 2020-09-24 03:52
Dear,

As i had old version of gcontact sync. I just overwrite it with 3.2.0 & now
able to download all 1500 + contacts, but do not forget to clear in setting
of logging etc.

I
